import { applyAction, legalActions, startHand } from "../engine/game";
import type { EngineState } from "../engine/types";
import { decideBot } from "../utils/pokerAi";
import { evaluateBestHand } from "../utils/pokerEvaluator";

export interface Card { suit:"hearts"|"diamonds"|"clubs"|"spades";rank:string;value:number }
export interface HandRank { rank:number;name:string;cards:Card[] }
export type Personality="tight"|"loose"|"aggressive"|"passive";
export interface PlayerStats { hands:number;vpip:number;pfr:number;betsRaises:number;calls:number;folds:number;showdowns:number;wins:number }
export interface Player { id:number;name:string;chips:number;hand:Card[];bet:number;folded:boolean;isDealer:boolean;isCurrentPlayer:boolean;handRank?:HandRank;personality?:Personality;hasActed?:boolean;contribution:number;stats:PlayerStats }
export type GamePhase="waiting"|"preflop"|"flop"|"turn"|"river"|"showdown";
export interface GameState { players:Player[];communityCards:Card[];pot:number;currentBet:number;phase:GamePhase;dealerIndex:number;currentPlayerIndex:number;deck:Card[];winner:Player|null;smallBlind:number;bigBlind:number;minRaise:number;winners:Player[];history:string[];lastDecision:string;handNumber:number;mode:"cash"|"tournament";paused:boolean;spectator:boolean;actionDelay:number;engine:EngineState|null }
const stats=():PlayerStats=>({hands:0,vpip:0,pfr:0,betsRaises:0,calls:0,folds:0,showdowns:0,wins:0});
const emptyState=():GameState=>({players:[],communityCards:[],pot:0,currentBet:0,phase:"waiting",dealerIndex:0,currentPlayerIndex:0,deck:[],winner:null,smallBlind:10,bigBlind:20,minRaise:20,winners:[],history:[],lastDecision:"",handNumber:0,mode:"cash",paused:false,spectator:false,actionDelay:800,engine:null});

export const usePoker=()=>{
  const gameState=useState<GameState>("pokerGame",emptyState);
  const metadata=new Map<number,{name:string;personality?:Personality;stats:PlayerStats}>();
  const ensureMetadata=()=>gameState.value.players.forEach(p=>metadata.set(p.id,{name:p.name,personality:p.personality,stats:p.stats||stats()}));
  const sync=(engine:EngineState,actionLog?:string)=>{const state=gameState.value;ensureMetadata();state.engine=engine;state.communityCards=engine.board;state.pot=engine.pot;state.currentBet=engine.currentBet;state.phase=engine.street;state.dealerIndex=engine.dealer;state.currentPlayerIndex=engine.turn;state.deck=engine.deck;state.smallBlind=engine.smallBlind;state.bigBlind=engine.bigBlind;state.minRaise=engine.lastFullRaise;state.handNumber=engine.handNumber;state.players=engine.players.map(p=>{const meta=metadata.get(p.id)||{name:p.id===0?"Você":`Jogador ${p.id+1}`,personality:p.id?"passive" as Personality:undefined,stats:stats()};return{id:p.id,name:meta.name,personality:meta.personality,stats:meta.stats,chips:p.chips,hand:p.hand,bet:p.bet,contribution:p.contribution,folded:p.folded,isDealer:p.id===engine.dealer,isCurrentPlayer:p.id===engine.turn&&engine.street!=="showdown",hasActed:p.acted,handRank:engine.street==="showdown"&&!p.folded?evaluateBestHand([...p.hand,...engine.board]):undefined}});state.winners=engine.winners.map(id=>state.players[id]!).filter(Boolean);state.winner=state.winners[0]||null;if(actionLog)state.history.unshift(actionLog);if(engine.street==="showdown")state.winners.forEach(p=>p.stats.wins++)};
  const initGame=(count=4,startingChips=1000)=>{const profiles:Personality[]=["tight","loose","aggressive","passive"];gameState.value=emptyState();gameState.value.players=Array.from({length:count},(_,id)=>({id,name:id===0?"Você":`Jogador ${id+1}`,chips:startingChips,hand:[],bet:0,folded:false,isDealer:id===0,isCurrentPlayer:false,personality:id?profiles[(id-1)%profiles.length]:undefined,contribution:0,stats:stats()}));metadata.clear();ensureMetadata()};
  const dealCards=()=>{const s=gameState.value;if(s.players.filter(p=>p.chips>0).length<2)return;let sb=s.smallBlind,bb=s.bigBlind,hand=s.handNumber+1;if(s.mode==="tournament"&&hand>1&&(hand-1)%5===0){sb*=2;bb*=2}s.history=[];const engine=startHand(s.players.map(p=>p.chips),{dealer:s.handNumber?undefined:s.dealerIndex,smallBlind:sb,bigBlind:bb,seed:Date.now(),handNumber:hand});sync(engine,`Mão ${hand} — blinds ${sb}/${bb}`);s.players.filter(p=>p.chips>0).forEach(p=>p.stats.hands++)};
  const perform=(action:Parameters<typeof applyAction>[1],label:string)=>{const s=gameState.value;if(!s.engine||s.paused)return;const actor=s.players[s.currentPlayerIndex];if(!actor)return;try{const before=s.engine.street;const next=applyAction(s.engine,action);if(action.type==="fold")actor.stats.folds++;if(action.type==="call"){actor.stats.calls++;if(before==="preflop")actor.stats.vpip++}if(action.type==="raiseTo"||action.type==="allIn"){actor.stats.betsRaises++;if(before==="preflop"){actor.stats.pfr++;actor.stats.vpip++}}if(next.street==="showdown"&&before!=="showdown")next.players.filter(p=>!p.folded).forEach(p=>metadata.get(p.id)!.stats.showdowns++);sync(next,`${actor.name}: ${label}`)}catch(error){s.history.unshift(error instanceof Error?error.message:"Ação ilegal")}};
  const fold=()=>perform({type:"fold"},"fold");
  const check=()=>perform({type:"check"},"check");
  const call=()=>{const amount=gameState.value.engine?legalActions(gameState.value.engine).call:0;perform({type:"call"},`call ${amount}`)};
  const raise=(increment:number)=>{const e=gameState.value.engine;if(!e)return;perform({type:"raiseTo",amount:e.currentBet+increment},`raise ${e.currentBet+increment}`)};
  const allIn=()=>perform({type:"allIn"},"all-in");
  const newRound=()=>{const s=gameState.value;if(s.players.filter(p=>p.chips>0).length<2)return;const oldDealer=s.dealerIndex;let dealer=oldDealer;do dealer=(dealer+1)%s.players.length;while(!s.players[dealer]?.chips);let sb=s.smallBlind,bb=s.bigBlind,hand=s.handNumber+1;if(s.mode==="tournament"&&hand>1&&(hand-1)%5===0){sb*=2;bb*=2}const engine=startHand(s.players.map(p=>p.chips),{dealer,smallBlind:sb,bigBlind:bb,seed:Date.now(),handNumber:hand});s.history=[];sync(engine,`Mão ${hand} — blinds ${sb}/${bb}`);s.players.filter(p=>p.chips>0).forEach(p=>p.stats.hands++)};
  const aiAction=()=>{const s=gameState.value,p=s.players[s.currentPlayerIndex];if(!p||!s.engine||s.paused||(p.id===0&&!s.spectator))return;const d=decideBot(p,s.communityCards,s.pot,s.currentBet,s.players.filter(x=>!x.folded&&x.id!==p.id).length,s.bigBlind);s.lastDecision=`${p.name} (${p.personality}): equity ${(d.equity*100).toFixed(0)}%, pot odds ${(d.potOdds*100).toFixed(0)}% → ${d.action}`;if(d.action==="fold")fold();else if(d.action==="check")check();else if(d.action==="call")call();else if(d.action==="allIn")allIn();else raise(d.raiseBy)};
  return{gameState,initGame,dealCards,fold,call,raise,check,allIn,newRound,aiAction,evaluateHand:(hand:Card[],board:Card[])=>evaluateBestHand([...hand,...board])};
};
