import{createDeck}from"./deck";import{seededRng}from"./random";import type{EnginePlayer,EngineState,LegalActions,PokerAction,Street}from"./types";import{distributePots,settlePots}from"../utils/pots";
const live=(p:EnginePlayer)=>!p.folded&&!p.allIn;
function nextEligible(players:EnginePlayer[],from:number,predicate=(p:EnginePlayer)=>p.chips>0&&!p.folded){for(let n=1;n<=players.length;n++){const i=((from+n)%players.length+players.length)%players.length;if(predicate(players[i]!))return i}return((from%players.length)+players.length)%players.length}
function take(p:EnginePlayer,amount:number){const paid=Math.min(amount,p.chips);p.chips-=paid;p.bet+=paid;p.contribution+=paid;p.allIn=p.chips===0;return paid}
export function startHand(stacks:number[],opts:{dealer?:number;smallBlind?:number;bigBlind?:number;seed?:number;handNumber?:number}={}):EngineState{if(stacks.filter(x=>x>0).length<2)throw new Error("São necessários dois jogadores com fichas");const players=stacks.map((chips,id)=>({id,chips,hand:[],bet:0,contribution:0,folded:chips===0,allIn:false,acted:false})),requested=opts.dealer??0,dealer=players[requested]?.chips?requested:nextEligible(players,requested),headsUp=players.filter(p=>p.chips>0).length===2,sb=headsUp?dealer:nextEligible(players,dealer),bb=nextEligible(players,sb),smallBlind=opts.smallBlind??10,bigBlind=opts.bigBlind??20,deck=createDeck(seededRng(opts.seed??Date.now()));for(let r=0;r<2;r++)for(const p of players.filter(p=>p.chips>0))p.hand.push(deck.pop()!);take(players[sb]!,smallBlind);take(players[bb]!,bigBlind);const turn=headsUp?sb:nextEligible(players,bb,p=>live(p));return{players,deck,board:[],street:"preflop",dealer,smallBlindIndex:sb,bigBlindIndex:bb,turn,smallBlind,bigBlind,currentBet:players[bb]!.bet,lastFullRaise:bigBlind,pot:players.reduce((n,p)=>n+p.contribution,0),handNumber:opts.handNumber??1,winners:[],log:[`Blinds ${smallBlind}/${bigBlind}`]}}
export function legalActions(s:EngineState,id=s.turn):LegalActions{const p=s.players[id];if(!p||id!==s.turn||s.street==="showdown"||!live(p))return{fold:false,check:false,call:0,minRaiseTo:null,maxRaiseTo:0,allIn:false};const call=Math.min(p.chips,Math.max(0,s.currentBet-p.bet)),max=p.bet+p.chips,min=s.currentBet+s.lastFullRaise;return{fold:true,check:call===0,call,minRaiseTo:max>=min?min:null,maxRaiseTo:max,allIn:p.chips>0}}
function roundComplete(s:EngineState){return s.players.filter(live).every(p=>p.acted&&p.bet===s.currentBet)}
function settle(s:EngineState){s.street="showdown";const awards=settlePots(s.players,s.board,s.dealer);distributePots(s.players,awards);s.winners=[...new Set(awards.flatMap(p=>p.winnerIds))];s.log.push(...awards.map((p,i)=>`Pote ${i+1} (${p.amount}): ${p.winnerIds.join(",")}`))}
function advance(s:EngineState){const contenders=s.players.filter(p=>!p.folded);if(contenders.length===1){const winner=contenders[0]!;winner.chips+=s.pot;s.winners=[winner.id];s.street="showdown";s.log.push(`Vitória por fold: ${winner.id}`);return}s.players.forEach(p=>{p.bet=0;p.acted=false});s.currentBet=0;s.lastFullRaise=s.bigBlind;if(s.street==="river"){settle(s);return}const count=s.street==="preflop"?3:1;for(let i=0;i<count;i++)s.board.push(s.deck.pop()!);s.street=({preflop:"flop",flop:"turn",turn:"river"}as Record<string,Street>)[s.street]!;const capable=s.players.filter(live);if(capable.length<2){advance(s);return}s.turn=nextEligible(s.players,s.dealer,live);s.log.push(s.street)}
export function applyAction(input:EngineState,action:PokerAction):EngineState{const s=structuredClone(input),p=s.players[s.turn]!,legal=legalActions(s),before=p.contribution;if(!legal.fold)throw new Error("Jogador não pode agir");if(action.type==="fold"){p.folded=true;s.log.push(`${p.id}: fold`)}else if(action.type==="check"){if(!legal.check)throw new Error("Check ilegal");s.log.push(`${p.id}: check`)}else if(action.type==="call"){if(!legal.call)throw new Error("Call ilegal");take(p,legal.call);s.log.push(`${p.id}: call`)}else if(action.type==="raiseTo"){if(action.amount>legal.maxRaiseTo||action.amount<(legal.minRaiseTo??Infinity))throw new Error("Raise ilegal");const old=s.currentBet;take(p,action.amount-p.bet);s.currentBet=p.bet;s.lastFullRaise=s.currentBet-old;s.players.filter(x=>x.id!==p.id&&live(x)).forEach(x=>x.acted=false);s.log.push(`${p.id}: raise ${action.amount}`)}else{const old=s.currentBet;take(p,p.chips);if(p.bet>s.currentBet){const increment=p.bet-s.currentBet;s.currentBet=p.bet;if(increment>=s.lastFullRaise){s.lastFullRaise=increment;s.players.filter(x=>x.id!==p.id&&live(x)).forEach(x=>x.acted=false)}}s.log.push(`${p.id}: all-in`)}s.pot+=p.contribution-before;p.acted=true;if(s.players.filter(x=>!x.folded).length===1||roundComplete(s))advance(s);else s.turn=nextEligible(s.players,p.id,live);return s}
